### ISSUE TITLE
payload generate:types generate does not work

### ISSUE THREAD

**Issue by amitsarkerr** [payloadcms/vercel-deploy-payload-postgres#2]
Hello,

I am trying to generate `payload generate:types` but getting error-

`node_modules/@payloadcms/plugin-cloud-storage/dist/adapters/vercelBlob/index.js:12
            throw new Error('The token argument is required for the Vercel Blob adapter.');`

Any suggestion how to fix it?

**Comment by denolfe** [comment]
Because Vercel's blob storage application requires a value to be passed, you must pass some sort of value into the token field. You can either set this env in your .env file or pass in a dummy value like this, and the generation should succeed.

```
adapter: vercelBlobAdapter({
  token: process.env.BLOB_READ_WRITE_TOKEN || 'dummy-value',
}),
```
